package com.example.ajcs.navigation

// routes for navigation
sealed class Screen(val route: String) {
    object Main : Screen("main")
    object Layouts : Screen("layouts")
    object Text : Screen("text")
    object Button : Screen("button")
    object TextField : Screen("text_field")
    object Images : Screen("images")
    object Card : Screen("card")
    object Checkbox : Screen("checkbox")
    object Chip : Screen("chip")
    object RadioButton : Screen("radio_button")
    object SearchBar : Screen("search_bar")
    object Slider : Screen("slider")
    object Switch : Screen("switch")
    object Snackbar : Screen("snackbar")
    object Fab : Screen("floating_action_button")
    object Lists : Screen("lists")
    object Grids : Screen("grids")
    object PullToRefresh : Screen("pull_to_refresh")
    object ProgressIndicators : Screen("progress_indicators")
    object Dialog : Screen("dialog")
    object DatePickers : Screen("date_pickers")
    object TimePickers : Screen("time_pickers")
    object Menus : Screen("menus")
    object NavigationDrawer : Screen("navigation_drawer")
    object TopAppBars : Screen("top_app_bars")
    object BottomAppBar : Screen("bottom_app_bar")
    object BottomSheets : Screen("bottom_sheets")
    object Tooltip : Screen("tooltip")
    object GoogleMap : Screen("google_map")
}